#' Mock Missing Inputs (The "Virtual Emma")
#'
#' Scans the paths for missing files. If a file is missing and is flagged as
#' "mockable", it creates a dummy file that allows the pipeline to proceed.
#'
#' @param paths_list List. The paths configuration.
#' @param contract Dataframe. Must contain 'key' and 'mock_type'.
#' @export
mock_missing_inputs <- function(paths_list, contract) {

  if (is.null(contract) || is.null(contract$mock_type)) {
    return(invisible(NULL))
  }

  # Filter for missing inputs that have a mock strategy
  inputs <- contract[contract$role == "INPUT" & !is.na(contract$mock_type), ]

  for (i in seq_len(nrow(inputs))) {
    key <- inputs$key[i]
    path <- paths_list[[key]]

    if (is.null(path)) next

    # If file is missing, we MOCK it
    if (!file.exists(path)) {
      cli::cli_alert_warning("Missing Input: {.file {path}}")
      cli::cli_alert_info("  --> Generating MOCK file (Type: {inputs$mock_type[i]})")

      # Create parent dir if needed
      dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)

      # Generate content based on file type
      type <- inputs$mock_type[i]

      if (type == "R_PIPELINE") {
        # Create an R script that does nothing (Identity Transformation)
        # Assuming the pipeline expects code like 'df %>% ...'
        # We write a comment or an identity function
        writeLines("# MOCK FILE GENERATED BY TEST SUITE\n# No edits applied.\nNULL", path)

      } else if (type == "EMPTY_CSV") {
        # Create a CSV with just headers (if known) or totally empty
        file.create(path)

      } else if (type == "XLSX") {
        # Create a minimal valid Excel file
        df <- data.frame(Note = "Mock Data")
        openxlsx::write.xlsx(df, path)
      }
    }
  }
}
